import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-folder',
  templateUrl: './folder.page.html',
  styleUrls: ['./folder.page.scss'],
})
export class FolderPage implements OnInit {
  public folder: string;
  public yemekler:any;

  constructor(private activatedRoute: ActivatedRoute) { }

  ngOnInit() {
    this.folder = this.activatedRoute.snapshot.paramMap.get('id');

    this.yemekler = [
      {adi:"Ispanak Çorbası",           kategori:"Çorba",     logo:"https://cdn.ye-mek.net/App_UI/Img/out/650/2019/01/terbiyeli-ispanak-corbasi-resimli-yemek-tarifi(11).jpg",                                                                    malzemeler:'Malzemeler :----------------------------------       1 bağ ıspanak -- 1 havuç -- Orta boy bir soğan -- 2 kaşık tereyağı -- Zeytinyağı -- Karabiber -- Tuz -- Etsuyu -- Su',                                                                                                                                                                                                                                                                                                                        tarif:'Tarif:Ispanak yapraklarını yıkayıp süzerek incecik doğrayın. Yağımızı tencereye alarak ince doğranmış soğanı kavurun. Rendelenmiş havucu ve ıspanakları ekleyerek 2-3 dakika kavurun. Suyunu ekleyerek sebzeler diriliğini kaybedene dek pişirin. Yumurta sarısını, unu, yoğurdu çırpın. Bir kepçe çorbamızdan ılıştırarak tencereye ekleyin. Bir taşım kaynatıp ocaktan almadan tuzunu ekleyip karabiberi de ekleyerek servis yapın.Afiyet olsun.!'},
      {adi:"Kuru Fasulye",              kategori:"Ana Yemek", logo:"https://i4.hurimg.com/i/hurriyet/75/750x422/5e787099d3806c27c4ef5369.jpg",                                                                                                    malzemeler:"Malzemeler :---------------------------------- 4 yemek kaşığı sıvı yağ -- 2 yemek kaşığı tereyağı -- 1 adet orta boy kuru soğan(yemeklik doğranmış) -- 1 yemek kaşığı domates salçası -- 500 gram kuru fasulye(1 gece önceden suda bekletilmilş) -- 3 su bardağı su -- 1 çay kaşığı tuz -- 1 çay kaşığı toz şeker -- 1/2 çay kaşığı tatlı toz kırmızı biber ",                                                                                                                                     tarif:"Tarif :4 yemek kaşığı sıvı yağ ve 2 yemek kaşığı tereyağını derin bir tencereye aktarın ve kızdırın.1 adet yemeklik doğranmış kuru soğanı da ekleyin ve pembeleşinceye kadar kavurun. -- Soğanlar kavrulduktan sonra 1 yemek kaşığı domates salçasını ekleyin ve kokusu çıkana kadar kavurun. -- Son olarak bir gece önceden suda beklettiğiniz kuru fasulyeleri de tencereye ekleyin. -- Sonra 1-2 dakika karıştırın ve 3 su bardağı su, 1 çay kaşığı kırmızı toz biber ve 1 çay kaşığı tuzu ekleyin, kapağını kapatıp fasulyeler yumuşayana kadar pişirin. -- Tane tane pişmiş pirinç pilavı ile servis edin, afiyet olsun!"},
      {adi:"Şehriyeli Pirinç Pilavı",   kategori:"Pilav",     logo:"https://im.haberturk.com/2019/10/16/ver1571221752/2531465_810x458.jpg",                                                                                                       malzemeler:"Malzemeler :----------------------------------         2 yemek kaşığı tereyağı -- 3 yemek kaşığı sıvı yağ -- 2 su bardağı pirinç -- Yarım su bardağı arpa şehriye -- 3 su bardağı sıcak su (tavuk suyu) -- Tuz",                                                                                                                                                                                                                                                                                   tarif:"Tarif :Pirinçler bol su ile yıkanarak, ılık tuzlu suda yarım saat kadar bekletilir. Bu süre sonunda, tuzlu suyu akıtılır ve pirinçler sudan geçirilerek, tüm suyu süzdürülür. -- Pilav tenceresinde tereyağı eritilir, sıvı yağ da eklenerek üzerine arpa şehriyeler eklenir. -- Şehriyenin rengi dönene kadar kavrulur. -- Pirinçler ilave edilerek, 2-3 dk daha kavrulur. -- Üzerine sıcak su eklenir ve tuzu ilave edilir. -- Tencerenin kapağı kapatılarak, yüksek ateşte fazla suyu çekip pirinçler göz göz oluncaya kadar, yani pirinçlerin üzerinde su çekilip pirinçler göründüğünde kısık ateşe alın ve tamamen suyu çekene kadar pişirin. (Yazının devamında süreler ile ilgili detaylı açıklamayı bulabilirsiniz.) -- Ocaktan aldıktan sonra, üzerine havlu kağıt koyarak kapağını tekrar kapatın ve demlenmesini bekleyin. -- Pilavı güzelce karıştırdıktan sonra servis yapabilirsiniz."},
      {adi:"Domates Çorbası",           kategori:"Çorba",     logo:"https://cdn.ye-mek.net/App_UI/Img/out/420/2012/02/9-domates-c3a7orbasc4b1.jpg",                                                                                               malzemeler:"Malzemeler :----------------------------------    1 yemek kaşığı tereyağı -- 2 çay bardağı süt(sıcak) -- 5 adet büyük boy domates -- 2 yemek kaşığı un -- 4 su bardağı sıcak et suyu",                                                                                                                                                                                                                                                                                                             tarif:"Tarif :1 yemek kaşığı tereyağını bir tavada eritin. 2 yemek kaşığı unu ekleyip kokusu çıkana kadar kısık ateşte, tereyağında kavurun. -- 5 adet rendelenmiş domatesi kavrulmuş un karışımına ekledikten sonra 5 dakika kadar pişirin. -- Üzerine 4 su bardağı sıcak et suyunu ilave edin. Kesilmemesi için küçük bir cezvede ısıttığınız 2 çay bardağı sütü azar azar ekleyip hızlıca karıştırın. -- Çorbayı kaynayana kadar orta ateşte ardından da kısık ateşte 15 dakika kadar pişirin. Daha pürüzsüz bir kıvam alması için blenderdan geçirin. -- Servis kaselerine aldığınız çorbayı, rendelenmiş kaşar peynir ilavesiyle sıcak olarak servis edin. Afiyet olsun!"},
      {adi:"Patlıcan Musakka",          kategori:"Ana Yemek", logo:"https://i12.haber7.net//haber/haber7/photos/2019/18/enfes_patlican_musakka_yemegi_nasil_yapilir_1556605944_3205.jpg",                                                         malzemeler:"Malzemeler :---------------------------------- 2 yemek kaşığı sıvı yağ -- 1 adet orta boy kuru soğan -- 3 adet orta boy çarliston biber -- 4 adet orta boy patlıcan -- 300 gram az yağlı kıyma -- 1 yemek kaşığı domates salçası -- 1 çay kaşığı tuz -- 1 çay kaşığı karabiber -- 1 çay kaşığı kimyon -- 2 adet domates -- 1 su bardağı su -- 1 su bardağı ayçiçek yağı",                                                                                                                          tarif:"Tarif :Patlıcanların uç kısımlarını aldıktan sonra kabuklarını alacalı şekilde soyun.Halka halka kestiğiniz patlıcanları, acısının çıkması için bol tuzlu suda bekletin. -- Sıvıyağını tavada kızdırın ve yemeklik doğradığınız soğanları üzerine ekleyip pembeleşinceye kadar kavurun.Üzerine biberi ilave edip kavurmaya devam edin. -- Kıymayı, salçayı, tuzu, karabiberi ve kimyonu da ekleyip pişirmeye devam edin. -- Küp doğradığınız domatesleri de ekleyip pişirmeye bırakın. Domatesler piştikten sonra ocaktan alın. -- Patlıcanları kızartmak için ayçiçek yağını geniş tabanlı bir tavada kızdırın. Acısının çıkması için tuzlu suda bekleyen patlıcanların suyunu süzdürün. Salata kurutucusu ya da kağıt havlu yardımıyla patlıcanları kuruladıktan sonra kızgın yağda arkalı önlü ters çevirerek kızartın. -- Altın rengini alan patlıcanları kızgın yağdan çıkarın ve ayrı bir tencereye dizin. -- Üzerine hazırladığınız kıymalı harcı da ekledikten -- Sonra 1 su bardağı su ilave edip 15 dakika pişirmeye bırakın. -- Sıcak olarak servis edin."},
      {adi:"Bulgur Pilavı",             kategori:"Pilav",     logo:"https://i.ytimg.com/vi/bJGMOTCZ1dA/maxresdefault.jpg",                                                                                                                        malzemeler:"Malzemeler :---------------------------------- 1 yemek kaşığı tereyağı -- 1 yemek kaşığı zeytinyağı -- 2 adet kuru soğan(yemeklik doğranmış) -- 1 diş sarımsak -- 2 adet yeşil biber(doğranmış) -- 1 yemek kaşığı domates salçası -- 1/2 yemek kaşığı biber salçası -- 2 su bardağı pilavlık bulgur -- 1 çay kaşığı tuz -- 1 çay kaşığı karabiber -- 1 çay kaşığı pul biber-- 1 tatlı kaşığı kekik -- 2 adet domates(rendelenmiş) -- 4 su bardağı su ",                                            tarif:"Tarif :Birer yemek kaşığı tereyağı ve zeytinyağını bir pilav tenceresinde kızdırın. Üzerine soğanları ilave edin. -- 2 adet yemeklik doğranmış kuru soğanı da tencereye ekleyin ve pembeleşinceye kadar kavurun. 1 adet ezilmiş sarımsak ve 2 adet doğranmış yeşil biberi de ekleyin ve kavurun. -- 1 yemek kaşığı domates salçası ve yarım yemek kaşığı biber salçasını da ekleyip kokusu çıkana kadar kavurun. -- Sonra 2 su bardağı pilavlık bulguru ekleyin. -- Baharat olarak 1'er çay kaşığı tuz, karabiber, pul biber ve 1 tatlı kaşığı kekik ilave edin. -- 2 adet rendelenmiş domatesi ilave edin. -- 4 su bardağı su ekledikten sonra tencerenin kapağını kapatıp pişmeye bırakın. -- Bulgurlar göz göz olup suyunu çektiğinde ocağın altını kapatın. -- Pilavınızın altını kapatın ve dinlenmeye bırakın. -- Bulgur pilavınız hazır, afiyet olsun!"},
      {adi:"Mercimek Çorbası",          kategori:"Çorba",     logo:"https://d2lswn7b0fl4u2.cloudfront.net/photos/pg-recipes-mercimek-corbasi-1574409415040.jpg",                                                                                  malzemeler:"Malzemeler :---------------------------------- 3 yemek kaşığı ayçiçek yağı -- 1 adet kuru soğan(iri doğranmış) -- 1 yemek kaşığı un -- 1 adet havuç(iri doğranmış) -- 1 adet patates(büyük boy, iri doğranmış) -- 1 tatlı kaşığı tuz -- 1 çay kaşığı karabiber -- 1,5 su bardağı kırmızı ya da sarı mercimek -- 6 su bardağı sıcak su(1 adet et su tablet ile hazırlanmış) -- 3 yemek kaşığı sıvı yağ -- 2 yemek kaşığı tereyağı -- 1 tatlı kaşığı kırmızı toz biber",                             tarif:"Tarif :Derin bir tencereye 3 yemek kaşığı sıvı yağ ekleyin. İri doğranmış 1 adet büyük soğanı sıvı yağ ile birlikte kavurun. -- Kavrulan soğanlara 1 yemek kaşığı unu ekleyin ve kokusu çıkıp, renk alana kadar kavurma işlemini sürdürün. İri parçalar halinde doğradığınız birer adet havuç ve patatesi tencereye aktarıp karıştırmaya devam edin. -- Tuz, karabiber ve bol suda yıkadıktan sonra suyunu süzdürdüğünüz 1,5 su bardağı mercimeği  de ilave edin ve son kez güzelce karıştırın. -- 6 su bardağı sıcak suyu da tencereye ilave edin. -- Ardından kapağını kapatın, patates ve havuçlar yumuşayana kadar ara ara karıştırarak 40 dakika kadar pişirin. -- Çorba piştikten sonra pürüzsüz bir kıvam alması için; el blenderından geçirin. 5 dakika daha pişirdikten sonra ocaktan alın. -- 3 yemek kaşığı sıvı yağ ve 2 yemek kaşığı tereyağını bir tavada kızdırın. Üzerine 1 tatlı kaşığı toz kırmızı biberi ekleyin ve 2 dakika yağı kızdırdıktan sonra ocaktan alın. -- Çorbayı bir kaseye alın ve üzerine kızdırdığınız yağdan gezdirip servis edin."},
    ];
    }

}
